steps:
  publish:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.merp.digital/${CI_REPO_OWNER}/woodpecker-scp
      registry: git.merp.digital
      tags: ${CI_COMMIT_BRANCH}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token

  publish-release:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: git.merp.digital/${CI_REPO_OWNER}/woodpecker-scp
      registry: git.merp.digital
      tags:
        - latest
        - ${CI_COMMIT_TAG}
      username: ${CI_REPO_OWNER}
      password:
        from_secret: cb_token
  when:
    - event: [tag]